import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../componentes/Header'
import dynamic from 'next/dynamic'
import 'bootstrap/dist/css/bootstrap.min.css'
const WeatherContainer = dynamic(
  () => import('../componentes/WeatherContainer'),
  {
    ssr: false,
  }
)

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
        />
      </Head>

      <Header />
      <WeatherContainer />
    </div>
  )
}

export default Home
